name: List Pull Requests

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Enter flag'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Run release script
      run: bash list_prs_action.sh ${{ github.event.inputs.ref_name }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
