name: Create Release

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Enter the ref name (branch or tag)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Run release script
      run: bash merged_script.sh -v ${{ github.event.inputs.ref_name }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
